packages:
  - 'app'
  - 'functions/*'
  - 'packages/*'
  # Internal tools
  - 'scripts/*'
  # Infrastructure
  - 'config/infrastructure'
  - 'global/utilities/infrastructure'
  - 'app/infrastructure'
  - 'functions/*/infrastructure'
