name = "{{ name }}"
handle = "{{ handle }}"

[[extends]]
target = "WatchThrough.Details.RenderAccessory"
module = "./WatchThroughAccessory.ts"
query = "./WatchThroughQuery.graphql"

# [[extends.conditions]]
# series.handle = "survivor"
