name = "{{ name }}"
handle = "{{ handle }}"

[[extends]]
target = "watch-through.details.accessory"
module = "./WatchThroughAccessory.ts"
query = "./WatchThroughQuery.graphql"

# [[extends.conditions]]
# series.handle = "survivor"
