name = "watch-internal-upload-clips"
main = "../build/output/clips-upload.js"

account_id = "9bfdb755def60e50760e33036c6f1624"
compatibility_date = "2024-04-05"

logpush = true
workers_dev = false

# Needs secrets:
# - JWT_SECRET

[[r2_buckets]]
binding = "CLIPS_ASSETS"
bucket_name = "watch-clips-assets"
