name = "watch-app"
main = "../build/server/server.js"

account_id = "9bfdb755def60e50760e33036c6f1624"
compatibility_date = "2025-03-09"

logpush = true
workers_dev = false
compatibility_flags = ["nodejs_compat"]
