name = "watch-email"
main = "../build/output/index.js"

account_id = "9bfdb755def60e50760e33036c6f1624"
compatibility_date = "2024-04-05"

logpush = true
workers_dev = false

# Needs the following environment variables:
# - JWT_SECRET
# - SENDGRID_API_KEY
