name = "{{ name }}"
handle = "{{ handle }}"

[[extends]]
target = "Series.Details.RenderAccessory"
module = "./SeriesAccessory.ts"
query = "./SeriesQuery.graphql"

# [[extends.conditions]]
# series.handle = "survivor"
