name: Run E2E tests
runs:
  using: 'composite'
  steps:
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
      shell: bash
    - name: Run Playwright tests
      run: pnpm test.e2e
      shell: bash
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
