name: Run E2E tests

inputs:
  secret:
    description: 'The secret to use for the E2E test header JWT'
    required: true
  preview-commit:
    description: 'The commit to use for the preview'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Get installed Playwright version
      id: playwright-version
      run: echo "PLAYWRIGHT_VERSION=$(pnpm tsx ./tests/e2e/scripts/playwright-version.ts)" >> $GITHUB_ENV
      shell: bash
    - name: Cache playwright binaries
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
    - run: pnpm exec playwright install --with-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
    - run: pnpm exec playwright install-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
    - name: Run Playwright tests
      run: pnpm test.e2e
      shell: bash
      env:
        PREVIEW_COMMIT: ${{inputs.preview-commit}}
        JWT_E2E_TEST_HEADER_SECRET: ${{inputs.secret}}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
