name: Deploy app assets

inputs:
  access-key-id:
    description: 'The R2 Access Key ID'
    required: true
  access-key-secret:
    description: 'The R2 Secret Access Key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure R2 credentials for AWS CLI
      run: |
        aws configure set region us-east-1
        aws configure set aws_access_key_id ${{ inputs.access-key-id }}
        aws configure set aws_secret_access_key ${{ inputs.access-key-secret }}
      shell: bash

    - name: Sync app assets to R2
      run: |
        aws s3 sync ./app/build/assets/ s3://watch-assets/assets/app/ --endpoint-url https://9bfdb755def60e50760e33036c6f1624.r2.cloudflarestorage.com --cache-control "public, max-age=31536000, immutable" --checksum-algorithm CRC32
      shell: bash
